name: indiekit
services:
  indiekit:
    image: ${INDIEKIT_IMAGE:?INDIEKIT_IMAGE must be set}
    pull_policy: always
    container_name: indiekit
    restart: always
    ports:
      - ${HTTP_PORT:-3000}:3000
    environment:
      - MONGO_URL=mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@mongo
      - PASSWORD_SECRET
      - SECRET
      - GITHUB_TOKEN
  mongo:
    image: mongo:8@sha256:b8806ee8207318a30316eca72257da4c146025a80fdcdb4c597e596af9233ee3
    restart: always
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
volumes:
  mongo: {}
