theme: dark

useEqualHeights: true

layout:
  Status:
    style: row
    columns: 1
  Apps:
    style: row
    columns: 2
  Platform:
    style: row
    columns: 2
  Monitoring:
    style: row
    columns: 2
  Machines:
    style: row
    columns: 2
  Backup:
    style: row
    columns: 2

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: false
  hideVisitURL: true
  provider: duckduckgo
