---
# renovate: datasource=github-releases depName=gitea/act_runner extractVersion=^v?(?<version>.*)$
act_runner_version: "0.2.11"

act_runner_user: act_runner
act_runner_group: act_runner
act_runner_binary_path: /usr/local/bin/act_runner
act_runner_config_dir: /etc/act_runner
act_runner_config_path: "{{ act_runner_config_dir }}/config.yaml"
act_runner_working_directory: /var/lib/act_runner
act_runner_runner_file: "{{ act_runner_working_directory }}/.runner"

act_runner_instance_url: ""
act_runner_registration_token: ""
act_runner_name: "{{ inventory_hostname_short | default(inventory_hostname) }}"
act_runner_labels:
  - "ubuntu-latest:docker://gitea/runner-images:ubuntu-latest"

act_runner_log_level: info
act_runner_capacity: 2
act_runner_job_timeout: 3h
act_runner_fetch_timeout: 5s
act_runner_fetch_interval: 2s
act_runner_instance_insecure: false

act_runner_cache_enabled: true
act_runner_cache_dir: "{{ act_runner_working_directory }}/cache"
act_runner_cache_host: "{{ inventory_hostname }}"
act_runner_cache_port: 8088
act_runner_cache_external_server: ""

act_runner_container_network: ""
act_runner_container_privileged: false
act_runner_container_options: ""
act_runner_container_workdir_parent: "{{ act_runner_working_directory }}/jobs"
act_runner_container_valid_volumes: []
act_runner_container_docker_host: unix:///var/run/docker.sock

act_runner_host_workdir_parent: "{{ act_runner_working_directory }}/host-jobs"
