services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.17.0@sha256:d570139f1891346131d02f8e4d1853100ae4846474958ca6c68cfe1648058467 #
    container_name: mealie
    restart: always
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      # PUID: 1000
      # PGID: 1000
      TZ: Europe/London
      BASE_URL: ${BASE_URL:?BASE_URL must be set}
      FORWARDED_ALLOW_IPS: '${FORWARDED_ALLOW_IPS:-192.168.1.9}'
      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SERVER: ${POSTGRES_SERVER:?POSTGRES_SERVER must be set}
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
      OIDC_AUTH_ENABLED: true
      OIDC_CONFIGURATION_URL: ${OIDC_CONFIGURATION_URL:?OIDC_CONFIGURATION_URL must be set}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_PROVIDER_NAME: "Kanidm"

volumes:
  mealie-data:
