---
renovate_service_name: "renovate"
renovate_timer_name: "{{ renovate_service_name }}.timer"

renovate_root_dir: "/opt/renovate"
renovate_config_path: "{{ renovate_root_dir }}/config.js"
renovate_env_path: "{{ renovate_root_dir }}/env"

renovate_docker_binary: "/usr/bin/docker"
renovate_docker_image: "ghcr.io/renovatebot/renovate:latest"
renovate_container_config_path: "/usr/src/app/config.js"
renovate_timeout_start_sec: "6h"

renovate_platform: "gitea"
renovate_endpoint: ""
renovate_token: "{{ vault_renovate_token | default('') }}"
renovate_git_author: "Renovate Bot <bot@renovateapp.com>"

renovate_autodiscover: true
renovate_dependency_dashboard: true
renovate_prune_stale_branches: true
renovate_onboarding: true
renovate_repositories: []
renovate_pr_hourly_limit: 10
renovate_labels:
  - dependencies
renovate_patch_grouping_enabled: true

renovate_dockerhub_username: ""
renovate_dockerhub_token: "{{ vault_dockerhub_token | default('') }}"
renovate_github_com_token: "{{ vault_github_com_token | default('') }}"

renovate_timer_on_calendar: "daily"
renovate_timer_persistent: true
