---
ingress_services:
  auth:
    domain: "auth.{{ cloud }}"
    upstream: "{{ hostvars[groups['auth'][0]].ansible_host }}:8443"
  beszel:
    domain: "beszel.{{ cloud }}"
    upstream: "{{ hostvars[groups['monpi'][0]].ansible_host }}:8090"
  freshrss:
    domain: "freshrss.{{ cloud }}"
    upstream: "{{ hostvars[groups['apps'][0]].ansible_host }}:8080"
  gitea:
    domain: "gitea.{{ cloud }}"
    upstream: "{{ hostvars[groups['git'][0]].ansible_host }}:3000"
  homebox:
    domain: "homebox.{{ cloud }}"
    upstream: "{{ hostvars[groups['apps'][0]].ansible_host }}:3100"
  homepage:
    domain: "homepage.{{ cloud }}"
    upstream: "{{ hostvars[groups['apps'][0]].ansible_host }}:3000"
  jellyfin:
    domain: "jellyfin.{{ cloud }}"
    upstream: "{{ hostvars[groups['jellyfin'][0]].ansible_host }}:8096"
  mealie:
    domain: "mealie.{{ cloud }}"
    upstream: "{{ hostvars[groups['apps'][0]].ansible_host }}:9000"
  mealie_enricher:
    domain: "mealie-enricher.{{ cloud }}"
    upstream: "{{ hostvars[groups['apps'][0]].ansible_host }}:9001"
  minio:
    domain: "minio.{{ cloud }}"
    upstream: "{{ truenas_ip }}:9002"
  ntfy:
    domain: "ntfy.{{ cloud }}"
    upstream: "{{ hostvars[groups['apps'][0]].ansible_host }}:8093"
  pihole:
    domain: "pihole.{{ cloud }}"
    upstream: "{{ hostvars[groups['dns'][0]].ansible_host }}:8080"
  proxmox:
    domain: "proxmox.{{ cloud }}"
    upstream: "{{ proxmox_ip }}:8006"
  truenas:
    domain: "truenas.{{ cloud }}"
    upstream: "{{ truenas_ip }}:81"
  uptime:
    domain: "uptime.{{ cloud }}"
    upstream: "{{ hostvars[groups['monpi'][0]].ansible_host }}:3001"

ingress_freshrss_greader_cors_origin: "https://stream.lab.paultibbetts.uk"
