---
gitea_runner_labels:
  - "ubuntu-latest:docker://gitea/runner-images:ubuntu-latest"
  - "ubuntu-24.04:docker://gitea/runner-images:ubuntu-24.04"

gitea_runner_instance_url: "https://gitea.cloud.paultibbetts.uk"
gitea_runner_name: "gitea-runner"
gitea_runner_cache_host: "gitea-runner.infra.home.arpa"

gitea_runner_registration_token: "{{ vault_gitea_runner_registration_token }}"
