services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v2.3.0@sha256:f820276654539cdc2cf0169f28188d135919a7984fad76d83d8d5ff1383f3705
    container_name: homepage
    network_mode: host # uses port 3000, required for DNS
    volumes:
      - ./config:/app/config
    env_file: .env
    restart: always
