galaxy_info:
  author: Paul Tibbetts
  description: Installs a DuckDNS updater script and cron job to keep a DNS record current.
  license: MIT
  min_ansible_version: "2.12"
  galaxy_tags:
    - ddns
    - duckdns
    - dns
    - cron
    - curl

dependencies: []
