---
- hosts: apps
  vars:
    apps_path: /srv/www/apps
    app_definitions:
      freshrss:
        env_template: "{{ playbook_dir }}/../templates/apps/freshrss/.env.j2"
        extra_copy_files:
          - freshrss-oidc.conf
      homepage:
        env_template: "{{ playbook_dir }}/../templates/apps/homepage/.env.j2"
        volume_dirs:
          - config
        extra_copy_dirs:
          - config
      homebox:
        env_template: "{{ playbook_dir }}/../templates/apps/homebox/.env.j2"
      mealie:
        env_template: "{{ playbook_dir }}/../templates/apps/mealie/.env.j2"
      mealie-enricher:
        env_template: "{{ playbook_dir }}/../templates/apps/mealie-enricher/.env.j2"
      ntfy:
        env_template: "{{ playbook_dir }}/../templates/apps/ntfy/.env.j2"
        volume_dirs:
          - data
  tasks:
    - name: Install Docker
      ansible.builtin.import_role:
        name: geerlingguy.docker
      become: true

    - name: Add ansible user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: true

    - name: Deploy compose app
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../roles/internal/common/tasks/deploy_compose_app.yaml"
      vars:
        app_name: "{{ app_def.key }}"
        app_path: "{{ apps_path }}/{{ app_def.key }}"
        compose_src: "{{ playbook_dir }}/../files/apps/{{ app_def.key }}/docker-compose.yaml"
        app_user: "{{ ansible_user }}"
        env_template: "{{ app_def.value.env_template | default(omit) }}"
        volume_dirs: "{{ app_def.value.volume_dirs | default([]) }}"
        extra_copy_dirs: "{{ app_def.value.extra_copy_dirs | default([]) }}"
        extra_copy_files: "{{ app_def.value.extra_copy_files | default([]) }}"
        enforce_volume_ownership: "{{ app_def.value.enforce_volume_ownership | default(false) }}"
      loop: "{{ app_definitions | dict2items }}"
      loop_control:
        loop_var: app_def
        label: "{{ app_def.key }}"
