---
- hosts: monpi
  become: true
  roles:
    - role: community.beszel.hub
  tags:
    - beszel
    - beszel_hub
    - hub

- hosts: all,!artpi,!pangolin.hcloud
  become: true
  roles:
    - role: community.beszel.agent
  vars:
    agent_public_key: "{{ vault_beszel_hub_public_key }}"
    agent_token: "{{ vault_beszel_agent_token }}"
    agent_hub_url: "{{ vault_beszel_agent_hub_url }}"
  tags:
    - beszel
    - beszel_agent
    - agent
  tasks:
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true
      tags:
        - restart

    - name: Restart beszel-agent to pick up updated token
      ansible.builtin.systemd:
        name: beszel-agent
        state: restarted
      tags:
        - restart
