---
- name: DNS
  hosts: dns
  gather_facts: true
  become: true
  vars:
    backup_script_directory: /usr/local/bin/
    backup_script_name: backup-pi-hole.sh
    backup_script: "{{ backup_script_directory }}{{ backup_script_name }}"
    healthcheck: "{{ dns_backup_healthcheck | default('curl -fsS -m 10 --retry 5 -o /dev/null https://healthchecks.example.com/ping/example-dns') }}"
  tasks:
    - name: Configure backups
      tags:
        - backup
      block:
        - name: Ensure backup directory exists
          ansible.builtin.file:
            path: /var/backups/pi-hole
            state: directory
            owner: ubuntu
            group: ubuntu
            mode: "0700"
        - name: Write backup script
          ansible.builtin.copy:
            src: "{{ (playbook_dir | dirname) ~ '/files/backups/' ~ backup_script_name }}"
            dest: "{{ backup_script }}"
            mode: "0755"
            owner: root
            group: root
        - name: Add script to CRON
          ansible.builtin.cron:
            name: pi-hole backup
            hour: "4"
            minute: "0"
            job: "{{ backup_script }} && {{ healthcheck }}"
