---
- hosts: tunnel:&site_edge
  gather_facts: true
  become: true
  roles:
    - role: geerlingguy.docker
    - role: pangolin
  tags:
    - pangolin

- hosts: tunnel:&site_home
  become: true
  vars:
    newt_endpoint: "{{ vault_newt_endpoint }}"
    newt_id: "{{ vault_newt_id }}"
    newt_secret: "{{ vault_newt_secret }}"
  roles:
    - role: newt
  tags:
    - newt
