postgresql_databases:
  - name: homebox
    owner: homebox
  - name: mealie
    owner: mealie
  - name: uptime_monitor
    owner: uptime_monitor

postgresql_users:
  - name: homebox
    password: "{{ vault_homebox_database_password }}"
    db: homebox
  - name: mealie
    password: "{{ vault_mealie_database_password }}"
    db: mealie
  - name: uptime_monitor
    password: "{{ vault_uptime_monitor_database_password }}"
    db: uptime_monitor

postgresql_hba_entries:
  - { type: local, database: all, user: postgres, auth_method: peer }
  - { type: local, database: all, user: all, auth_method: peer }
  - {
      type: host,
      database: all,
      user: all,
      address: "127.0.0.1/32",
      auth_method: md5,
    }
  - {
      type: host,
      database: all,
      user: all,
      address: "::1/128",
      auth_method: md5,
    }
  - {
      type: host,
      database: homebox,
      user: homebox,
      address: "{{ postgres_client_cidr }}",
      auth_method: md5,
    }
  - {
      type: host,
      database: mealie,
      user: mealie,
      address: "{{ postgres_client_cidr }}",
      auth_method: md5,
    }
  - {
      type: host,
      database: uptime_monitor,
      user: uptime_monitor,
      address: "{{ postgres_client_cidr }}",
      auth_method: md5,
    }

postgres_users_no_log: false
