---
- name: Common for all hosts
  hosts: all
  become: true
  ignore_unreachable: true
  roles:
    - { role: common, tags: [common] }

- ansible.builtin.import_playbook: playbooks/databases.yaml
  tags: [databases]
- ansible.builtin.import_playbook: playbooks/auth.yaml
  tags: [auth]
- ansible.builtin.import_playbook: playbooks/git.yaml
  tags: [git]
- ansible.builtin.import_playbook: playbooks/apps.yaml
  tags: [apps]
- ansible.builtin.import_playbook: playbooks/monitoring.yaml
  tags: [monitoring]
- ansible.builtin.import_playbook: playbooks/ingress.yaml
  tags: [ingress]
- ansible.builtin.import_playbook: playbooks/dns.yaml
  tags: [dns]
- ansible.builtin.import_playbook: playbooks/tunnel.yaml
  tags: [tunnel]
- ansible.builtin.import_playbook: playbooks/vpn.yaml
  tags: [vpn]
- ansible.builtin.import_playbook: playbooks/renovate.yaml
  tags: [renovate]
