---
- name: Common for all hosts
  hosts: all
  become: true
  ignore_unreachable: true
  roles:
    - { role: common, tags: [common] }

- name: Databases
  ansible.builtin.import_playbook: playbooks/databases.yaml
  tags: [databases]
- name: Auth
  ansible.builtin.import_playbook: playbooks/auth.yaml
  tags: [auth]
- name: Git
  ansible.builtin.import_playbook: playbooks/git.yaml
  tags: [git]
- name: Apps
  ansible.builtin.import_playbook: playbooks/apps.yaml
  tags: [apps]
- name: Monitoring
  ansible.builtin.import_playbook: playbooks/monitoring.yaml
  tags: [monitoring]
- name: Ingress
  ansible.builtin.import_playbook: playbooks/ingress.yaml
  tags: [ingress]
- name: DNS
  ansible.builtin.import_playbook: playbooks/dns.yaml
  tags: [dns]
- name: Tunnel
  ansible.builtin.import_playbook: playbooks/tunnel.yaml
  tags: [tunnel]
- name: VPN
  ansible.builtin.import_playbook: playbooks/vpn.yaml
  tags: [vpn]
- name: Renovate
  ansible.builtin.import_playbook: playbooks/renovate.yaml
  tags: [renovate]
